version: '2'

volumes:
  craftcms-data:
  mysql-data:
  craftcms-logs:

services:
    web:
      image: grana/craftcms-docker:latest
      ports:
        - 80:80
      volumes:
        - craftcms-logs:/var/log
        - craftcms-data:/usr/share/nginx
      links:
        - mysql
        - redis
      # env vars are replaced in .env
      environment:
        # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
        LANG: C.UTF-8

        # REDIS is linked
        REDIS_HOST: redis
        REDIS_PORT_6379_TCP: tcp://redis:6379

        # DB is linked
        DB_DRIVER: mysql
        DB_SERVER: mysql
        DB_DATABASE: craft3
        DB_PASSWORD: secret
        DB_SCHEMA: public
        DB_PORT: '3306'
        DB_USER: craft3
        LANG: C.UTF-8

    mysql:
      image: mysql:5.7
      environment:
        MYSQL_USER: craft3
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: craft3
      volumes:
        # Persistent data
        - mysql-data:/var/lib/mysql

    redis:
      image: redis:4.0.10-alpine
      volumes:
        - /tmp/redis:/data
